// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1 
    FROM users 
    WHERE email = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserIsAdmin = `-- name: CheckUserIsAdmin :one
SELECT EXISTS(
    SELECT 1 
    FROM users 
    WHERE id = $1::uuid AND role_id = (SELECT id FROM roles WHERE name = 'Admin') AND deleted_at IS NULL
) AS is_admin
`

func (q *Queries) CheckUserIsAdmin(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserIsAdmin, userID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, email, password_hash, created_at, updated_at, deleted_at, role_id
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RoleID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
UPDATE users 
SET 
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role_id
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	RoleID       uuid.UUID `json:"role_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, created_at 
FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT 
    u.id as user_id,
    u.name as user_name,
    r.id as role_id,
    r.name as role_name
FROM users u
JOIN roles r ON u.role_id = r.id
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetUserRoleRow struct {
	UserID   uuid.UUID `json:"user_id"`
	UserName string    `json:"user_name"`
	RoleID   uuid.UUID `json:"role_id"`
	RoleName string    `json:"role_name"`
}

func (q *Queries) GetUserRole(ctx context.Context, id uuid.UUID) (GetUserRoleRow, error) {
	row := q.db.QueryRow(ctx, getUserRole, id)
	var i GetUserRoleRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.RoleID,
		&i.RoleName,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT 
    u.id,
    u.name,
    COUNT(DISTINCT i.id) as total_income_records,
    COUNT(DISTINCT e.id) as total_expense_records,
    COUNT(DISTINCT b.id) as total_budgets
FROM users u
LEFT JOIN income i ON u.id = i.user_id AND i.deleted_at IS NULL
LEFT JOIN expenses e ON u.id = e.user_id AND e.deleted_at IS NULL
LEFT JOIN budgets b ON u.id = b.user_id AND b.deleted_at IS NULL
WHERE u.id = $1 AND u.deleted_at IS NULL
GROUP BY u.id, u.name
`

type GetUserStatsRow struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	TotalIncomeRecords  int64     `json:"total_income_records"`
	TotalExpenseRecords int64     `json:"total_expense_records"`
	TotalBudgets        int64     `json:"total_budgets"`
}

func (q *Queries) GetUserStats(ctx context.Context, id uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, id)
	var i GetUserStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalIncomeRecords,
		&i.TotalExpenseRecords,
		&i.TotalBudgets,
	)
	return i, err
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT u.id::uuid, u.name::varchar(255), u.email::varchar(255), r.name::varchar(255) as role
FROM roles r
LEFT JOIN users u ON u.role_id = r.id AND u.deleted_at IS NULL
WHERE r.name = $1
ORDER BY u.created_at DESC
`

type ListUsersByRoleRow struct {
	UID    uuid.UUID `json:"u_id"`
	UName  string    `json:"u_name"`
	UEmail string    `json:"u_email"`
	Role   string    `json:"role"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, name string) ([]ListUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByRoleRow
	for rows.Next() {
		var i ListUsersByRoleRow
		if err := rows.Scan(
			&i.UID,
			&i.UName,
			&i.UEmail,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    name = $2,
    email = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, created_at, updated_at, deleted_at, role_id
`

type UpdateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RoleID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users 
SET 
    password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users 
SET 
    role_id = $1::uuid,
    updated_at = CURRENT_TIMESTAMP
WHERE users.id = $2::uuid AND deleted_at IS NULL
RETURNING (
    SELECT json_build_object(
        'user_id', u.id,
        'user_name', u.name,
        'role_id', r.id,
        'role_name', r.name
    )
    FROM users u
    JOIN roles r ON r.id = $1::uuid
    WHERE u.id = $2::uuid
)
`

type UpdateUserRoleParams struct {
	RoleID uuid.UUID `json:"role_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.RoleID, arg.UserID)
	var json_build_object []byte
	err := row.Scan(&json_build_object)
	return json_build_object, err
}
